### ISSUE TITLE
Add additional gem owner to enable our bots to publish the gem.

### ISSUE THREAD

**Issue by jordansissel** [Icinga/logstash-output-icinga#3]
We use a chatbot on Slack to do most plugin publishing, and it authenticates against rubygems.org with the account `dev_ops@elastic.co`

@bobapple - can you run this? `gem owner logstash-output-icinga -a dev_ops@elastic.co` ?

**Comment by bobapple** [comment]
@jordansissel thank you for copying the repo!
I added `dev_ops@elastic.co` as owner, current owners are as follows:

``` shell
Owners for gem: logstash-output-icinga
- dev_ops@elastic.co
- info@icinga.com
```

**Comment by jordansissel** [comment]
Perfect!
