### ISSUE TITLE
Implement support for ignore_on_error

### ISSUE THREAD

**Issue by gunnarbeutner** [Icinga/logstash-output-icinga#4]
The ignore_on_error attribute should be set by default - and maybe make this user-configurable.

See https://github.com/Icinga/icinga2/issues/5797 for the documentation ticket in the Icinga 2 project.

**Comment by lazyfrosch** [comment]
The basic idea is that Icinga 2 can drop those auto-generated services, similar to how we cleanup dangling comments / downtimes.

Edit: *when the host disappears from config

**Comment by bobapple** [comment]
Makes sense to me. I will implement this as default behaviour for the next version.
