### ISSUE TITLE
does it support icinga 1x ?

### ISSUE THREAD

**Issue by maraev** [Icinga/logstash-output-icinga#6]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Plugin version (`bin/logstash-plugin list '*icinga*'`):
* Logstash version (`bin/logstash -V`):
* Icinga 2 version (`icinga2 --version`):
* Ruby version (`ruby -V`):
* Operating System and version:

**Comment by lazyfrosch** [comment]
No, the output is built for Icinga 2 and its API, so actions can be handled remotely and with a modern API.
